#!/bin/sh
#
# @name Gazebo s2000
#
# @type Octocopter X geometry
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 14
param set CA_METHOD 1


param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 0.51
param set-default CA_ROTOR0_PY 0.21
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.51
param set-default CA_ROTOR1_PY -0.21
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR2_PX 0.21
param set-default CA_ROTOR2_PY 0.51
param set-default CA_ROTOR2_KM 0.05

param set-default CA_ROTOR3_PX -0.51
param set-default CA_ROTOR3_PY 0.21
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 0.51
param set-default CA_ROTOR4_PY -0.21
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -0.21
param set-default CA_ROTOR5_PY -0.51
param set-default CA_ROTOR5_KM 0.05

param set-default CA_ROTOR6_PX 0.21
param set-default CA_ROTOR6_PY -0.51
param set-default CA_ROTOR6_KM -0.05

param set-default CA_ROTOR7_PX -0.21
param set-default CA_ROTOR7_PY 0.51
param set-default CA_ROTOR7_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108


param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 0







param set-default MC_ROLLRATE_P 0.18
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLLRATE_D 0.007
param set-default MC_ROLL_P 5.20

param set-default MC_PITCHRATE_P 0.18
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.007
param set-default MC_PITCH_P 5.5

param set-default MC_YAWRATE_P 0.23
param set-default MC_YAWRATE_I 0.15
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAW_P 5.90




# param set MC_ROLLRATE_FF  0.20
# param set MC_PITCHRATE_FF 0.20

# param set MC_YAWRATE_FF   0.15


# param set-default MC_ROLLRATE_P 0.165
# param set-default MC_ROLLRATE_I 0.202
# param set-default MC_ROLLRATE_D 0.0004
# param set-default MC_ROLL_P 5.78

# param set-default MC_PITCHRATE_P 0.159
# param set-default MC_PITCHRATE_I 0.198
# param set-default MC_PITCHRATE_D 0.0004
# param set-default MC_PITCH_P 6.01

# param set-default MC_YAWRATE_P 0.118
# param set-default MC_YAWRATE_I 0.18
# param set-default MC_YAWRATE_D 0.0
# param set-default MC_YAW_P 6.5



param set-default BAT1_N_CELLS 6.0

param set-default MPC_THR_HOVER 0.50